/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import Huffman.HuffmanLib;
import java.awt.Dimension;
import java.awt.Graphics;

/**
 *
 * @author Daniel
 */
public class Panelin extends javax.swing.JPanel {
    public HuffmanLib huf;
    /**
     * Creates new form Panelin
     */
    public Panelin() {
        initComponents();
    }
    /**
     * Creates new form Panelin
     */
    public Panelin(HuffmanLib huf) {
        this.huf = huf;
        initComponents();
    }

    public void setHuf(HuffmanLib huf) {
        this.huf = huf;
    }
    
    @Override
    public void paint(Graphics g) {
        super.paint(g); //To change body of generated methods, choose Tools | Templates.
        //g.drawString(Integer.toString(t.Colas.get(t.Colas.size()-1).id), WIDTH/2, 10);
        if (this.huf==null){
            return;
            //System.out.println(this.huf);
        }
        int n = 0;
        for (int i = 0; i<huf.Tablas.get(huf.Tablas.size()-1).cars.size();i++){
            if (huf.crips.get(huf.Tablas.get(huf.Tablas.size()-1).cars.get(i)).length()>n){
                n=huf.crips.get(huf.Tablas.get(huf.Tablas.size()-1).cars.get(i)).length();
            }
        }
        int m=40;//(2^(n+1))-1;
        for (int i = 0; i < huf.Tablas.get(huf.Tablas.size()-1).cars.size();i++){
            int prev=(int)Math.pow(2.0, n);
            g.drawOval(prev*m, 0, 30, 30);
            g.drawString(Integer.toString(huf.Tablas.get(huf.Tablas.size()-1).Colas.get(huf.calcularN()-1).id), m*prev+5, 15);
            int acT = huf.calcularN()-1;
            for (int j = 0; j < huf.crips.get(huf.Tablas.get(huf.Tablas.size()-1).cars.get(i)).length(); j++){
                int t = prev;
                if ("1".equals(huf.crips.get(huf.Tablas.get(huf.Tablas.size()-1).cars.get(i)).split("")[j])){
                    prev += Math.pow(2,(n-(j+1)));
                    acT=huf.Tablas.get(huf.Tablas.size()-1).Colas.get(acT).hidjoder;
                }else{
                    //g.drawLine(prev, 40*(j), prev - 40*(n-j), 40*(j+1));
                    prev -= Math.pow(2,(n-(j+1)));
                    acT=huf.Tablas.get(huf.Tablas.size()-1).Colas.get(acT).hidjoizq;
                    //prev -= 40*(n-j);
                }
                //System.out.println(huf.crips.get(huf.Tablas.get(huf.Tablas.size()-1).cars.get(i)));
                //System.out.println(prev);
                g.drawLine((t*m)+15, m*j+15, m*prev+15, m*(j+1)+15);
                //g.drawOval(prev*m, m*(j+1), 30, 30);
                if (!huf.Tablas.get(huf.Tablas.size()-1).Colas.get(acT).cad.equals("")){
                    g.drawString(huf.Tablas.get(huf.Tablas.size()-1).Colas.get(acT).cad, m*prev+10, m*(j+1)+25);
                    g.drawString(huf.crips.get(huf.Tablas.get(huf.Tablas.size()-1).Colas.get(acT).cad), m*prev+5, m*(j+1)+40);
                }else{
                    g.drawString(Integer.toString(huf.Tablas.get(huf.Tablas.size()-1).Colas.get(acT).id), m*prev+5, m*(j+1)+15);
                }
            }
        }
        this.setPreferredSize(new Dimension((int)(Math.pow(2,n+1))*m, (n+2)*m));
        /*for (int i = 0; i<huf.Tablas.get(huf.Tablas.size()-1).cars.size();i++){
            if (huf.Tablas.get(huf.Tablas.size()-1).Colas.get(huf.calcularN()).)
        }*/
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField1 = new javax.swing.JTextField();

        jTextField1.setText("jTextField1");

        setBackground(new java.awt.Color(255, 240, 250));
        setAutoscrolls(true);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables
}
